### ISSUE TITLE
Getting started with the Java client

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#12]
Question:
*I am really confused in using Route Optimization API. I just cloned the [directions-api-vrp-java-client](https://github.com/karussell/directions-api-vrp-java-client). Now i want to test the example given. So what should i do after cloning the API from the repository. Could you guys be able to provide a documentation for this as well. I am just a beginner in android programming.*

Answer:
*After you cloned the repository execute the steps described under 'Maven' to build the client jar locally and include the maven xml snippet in your project. Then use [one of the examples](https://github.com/karussell/directions-api-vrp-java-client/tree/master/src/main/java/com/graphhopper/api/vrp/example) to use the API for your needs.*

**Comment by karussell** [comment]
Question
*Do i copy those all jar files under my project's lib folder?**

Answer
*Yes, all jars are currently required, plus directions-api-vrp-java-client-0.4.2.jar in the target folder.

But the simplest would be if you use Maven or gradle. As for Android development the preferred IDE is now IntelliJ which uses gradle as build system this should be very easy and you only need to include the snippet to the directions-api-vrp-java-client which then fetches all dependencies automatically.*

**Comment by Geo-Trackers** [comment]
((((((you only need to include the snippet to the directions-api-vrp-java-client which then fetches all dependencies automatically.))))
could you explain me in more detail...i am confused in this statement......Thank you

**Comment by karussell** [comment]
Please see how to handle depencencies for gradle or maven in your IDE. E.g. [here](http://stackoverflow.com/questions/16626878/android-studio-and-gradle-dependency-integration) and [here](http://stackoverflow.com/questions/16671277/maven-dependencies-with-android-studio-gradle)
