### ISSUE TITLE
Progress of alpha release for Route Optimization / Tour Optimization API

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api#20]

**Comment by oblonski** [comment]
Request validation is now much more restrictive since it now checks also values and values types. It now checks for example whether 'size' is an array and whether the items within the array which are basically the size dimensions of your pickup/delivery are of type INTEGER. If not, you get an error message with a detailed description of what went wrong to easily adjust your input request. This makes sure (among others) that our system does not solve an entirely different problem (compared to what you have actually posted) and does not provide you with unexpected results.

**Comment by karussell** [comment]
We can close here I think. See [this blog post](https://graphhopper.com/blog/2015/11/02/graphhopper-route-optimization-api-goes-beta/) for more information.
