### ISSUE TITLE
Support for Open Location Code

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#31]
We should not only support GPS coordinates but also [open location code](https://github.com/google/open-location-code/blob/master/docs/olc_definition.adoc) from Google. Standing under Apache License. See [here](https://github.com/google/open-location-code/blob/master/docs/comparison.adoc) for a good comparison where open location code stands out from its logical point of view and being pure algorithmic based as well as the code license.

We need to clarify
- [x] license, clear answer at https://github.com/google/open-location-code/issues/48 
- [x] elevation support? No, there is no elevation/level support, https://github.com/google/open-location-code/issues/47

An alternative would be https://github.com/roberdam/Xaddress

**Comment by karussell** [comment]
We won't support this

**Comment by mmd-osm** [comment]
Apologies for hijacking this issue a bit. Maybe you've seen the discussion to implement OLC on osm.org which has attracted a lot of attention in recent years: https://github.com/openstreetmap/openstreetmap-website/issues/1807.

As you've seem to have spent some time analyzing OLC in more detail and eventually decided against it, your reasoning might be helpful for the discussion on osm.org as well.

**Comment by karussell** [comment]
I prefer OLC over all other existing "codes". But IMO the client can&should decode OLC and use coordinates for all API related stuff.
