### ISSUE TITLE
Include live docs

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#32]
ReDoc is really useful for displaying an explorable API with swagger spec. See e.g. [here](https://rebilly.github.io/ReDoc/?url=https://apis-guru.github.io/api-models/graphhopper.com/1.0/swagger.yaml)

We should set this up on our servers.

**Comment by RomanGotsiy** [comment]
@karussell, we are preparing our first public release so we will appreciate your feedback if there are any mistakes/unclear thing in docs.

BTW: to simplified deployment you can use ReDoc from [cdn](https://github.com/Rebilly/ReDoc/blob/master/README.md#1-install-redoc).
Also, you can check out our new project (beta) [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo). It will simplify your workflow.

**Comment by karussell** [comment]
We have this now done :)
