### ISSUE TITLE
reverse geocoding result should always include name entry

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#36]
Bad example where name is missing -> https://graphhopper.com/api/1/geocode?point=52.5487429714954,-1.81602098644987&reverse=true&key=xyz

**Comment by timminata** [comment]
Thanks for creating the issue guys, has anyone been looking into it?

**Comment by karussell** [comment]
Not yet, sorry.

**Comment by davenewza** [comment]
@karussell: Is it possible to suggest an interim solution. If `name `doesn't exist, could we perhaps concatenate `street`, `city`, `state `and `country` (if they aren't empty)?

**Comment by karussell** [comment]
Related https://github.com/komoot/photon/issues/199

**Comment by karussell** [comment]
@davenewza Probably it would be more consistent to use a fallback in the following way:

 * use street if available, if not use:
 * city if available (plus postcode?), if not use:
 * state if available if not use:
 * country

This way it behaves similar for similar queries, e.g. if you query for an address you just get the street as name.

Or what would be the best for your use case?

**Comment by karussell** [comment]
This is now implemented as described.
