### ISSUE TITLE
Isochrone API

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#4]
What is an isochrone calculation? Is is also called *reachability* or *walkability*. Read at [Wikipedia](http://en.wikipedia.org/wiki/Isochrone_map).

Please contact us to take part as an alpha tester. See [a simple example](https://graphhopper.com/api/1/examples/#isochrone) and [the Isochrone API documentation](https://graphhopper.com/api/1/docs/isochrone/)

[Contact us](https://graphhopper.com/#contact) to become an alpha tester!

![isochrone-example](https://cloud.githubusercontent.com/assets/129644/13076281/9ea50454-d4b1-11e5-9251-fa1c6b204043.png)

**Comment by davenewza** [comment]
Has their been any movement on this feature?

**Comment by karussell** [comment]
No, it is not yet production ready, sorry.

**Comment by karussell** [comment]
We have improved this. Please contact us to take part as an alpha tester.
