### ISSUE TITLE
Network not found but should at least for hike or mtb

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#46]
When certain areas are disconnected from the main network we remove them completely to avoid start and end requests there, which would result in 'connection not found' issues if the other point is in the main network.

Probably this area is [too small](https://graphhopper.com/maps/?point=57.039224%2C-5.683172&point=57.06281%2C-5.683193&locale=en&vehicle=hike).

**Comment by karussell** [comment]
It is indeed the problem I guessed (too few nodes). Will fix this via a configuration, if this does not help we could reset to the default config (of min_network_size) and remove small subnetworks only if they are also small "area-wise" as the suspected area is not small (15km²).

**Comment by karussell** [comment]
This is fixed now

**Comment by karussell** [comment]
Now we get problems with islands due to access restrictions e.g. [here](https://graphhopper.com/maps/?point=51.160931%2C-0.190126&point=51.161449%2C-0.18724) and [here](https://graphhopper.com/maps/?point=53.572604%2C9.880738&point=53.57334%2C9.88048). We have to revert this change for the time being and consolidate how to properly fix this.

**Comment by michaz** [comment]
Could we, instead of _removing_ the islands, connect them, by a synthetic edge, to their surroundings?

This would be closer to physical reality: You _can_ get from a footpath on an airport to the outside. The problem is not that the footpath exists, but that it appears disconnected in the model.

**Comment by michaz** [comment]
(Prof. always calls this 'bushwacking'. Assuming in a model that you _can_ get from every place to every other, just very slowly and inconveniently.)

**Comment by karussell** [comment]
But how would such a connection heuristic look like? What about dangerous areas? Maybe for foot/bike there is a heuristic, but what about cars or trucks?

One solution to the island problem could be a many to many routing, so one could route within the islands. But then there is another problem: how do you weigh in the beeline distance vs. the time (the actual weighting)? A similar problem we have in map matching.

Also more problematic are cases where there is no disconnected island but instead the direct connection is missing and a huge detour has to be made.

**Comment by karussell** [comment]
Where I see a big problem are islands that are indirectly introduced per-request. Example: we block ways for vehicles with width=2m, then islands are easily created and a full graph scan is the result. Hmmh, this could be reduced if we use a similar approach that you defined for 'pt': detect 'how far' the destination is without the restriction (define this as X) and then search further but not longer than `2*X`

**Comment by michaz** [comment]
Yeah. I'm currently _trying_ to see how far I get with this (I'm doing multi-criteria by default):

- All constraints are "soft" in the way that they're not modelled as removed edges where you cannot even _be_ in the first place or which aren't explored, but by weight = large or weight = infinity.
- We are responsible for terminating the search.
- I'm trying to see "terminating the search" as: There is some mode which "always works". For me this is walking, and once there is a walking solution available (which is automatically "very bad" because of the queue order (travel time)), any other solutions are not considered to "improve" that any more. -> Termination.

**Comment by karussell** [comment]
> We are responsible for terminating the search. (So the user can't do DOS attacks by specifying weird cost functions.)

We should be safe due to the maximum number of visited nodes. 

Still this is interesting: if we e.g. increase a weight of a bridge too much the search might be successful but performance could suffer as too many unrelated nodes have to be explored (before the bridge is further investigated and the destination is found). And so we should somehow guide the user/developer that a too extreme weighting difference (from 'default') can be very bad for performance. Or if we at some point make a lot more things configurable per request we should only allow factors from 1 to 5 or something, not arbitrary 'bad'. Hmmh, but blocking/infinity is arbitrary bad and often required.

**Comment by boldtrn** [comment]
> Could we, instead of removing the islands, connect them, by a high-penalty synthetic edge, to their surroundings?

Do we know the number of islands? Maybe we could look at the most important (biggest) ones and try to fix the underlying data. For example creating issues for OSM, so locals can fix it, or sometimes fixes are obvious. For example I fixed a road once that was disconnected by one OSM contributor that probably made a mistake by disconnecting it.

I would assume that most areas are accessible, but the mapping is simply incorrect/insufficient.

**Comment by karussell** [comment]
The number of those islands is usually huge (>15m). Just have a look into the world wide import where it says e.g. edges: 177458975, nodes 132784561, there were 17 675 148 subnetworks. removed them => 4611970 less nodes

**Comment by boldtrn** [comment]
> The number of those islands is usually huge (>15m)

Thanks for the clarification. That makes things more complicated :(.

**Comment by karussell** [comment]
Another problem occurs [here](http://www.openstreetmap.org/way/434310193#map=13/50.8554/-128.0651), which [should give a route](https://graphhopper.com/maps/?point=50.834782%2C-128.19118&point=50.867288%2C-128.092234&vehicle=foot).

**Comment by boldtrn** [comment]
> Another problem occurs here, which should give a route for hike.

The reason for this seems to be that it is disconnected here at the [parking lot](http://www.openstreetmap.org/way/184432435). This might be also fixable by routing over areas.

**Comment by karussell** [comment]
Seems to be mostly fixed and if not will continued at https://github.com/graphhopper/graphhopper/issues/897
