### ISSUE TITLE
Matrix API pass less than 3 points

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api#54]
When passing less than 3 points to the matrix api the results are just empty:
```
{
distances: [
[
0
]
],
times: [
[
0
]
],
weights: [
[
0
]
],
info: {
copyrights: [
"GraphHopper",
"OpenStreetMap contributors"
]
}
}
```

I would have expected an exception?

When passing no points, I get an exception:
```
{
message: "Bad Request",
hints: [
{
message: "Too few points. From:0, to:0"
}
]
}
```

**Comment by karussell** [comment]
> When passing less than 3 points to the matrix api the results are just empty:

That would be a bug, do you have an example request?

**Comment by boldtrn** [comment]
> That would be a bug, do you have an example request?

Sure, here is a sample request:
```
https://graphhopper.com/api/1/matrix?point=49.932707%2C11.588051&type=json&vehicle=car&debug=true&out_array=weights&out_array=times&out_array=distances&key=[KEY]
```

**Comment by oblonski** [comment]
When you pass one point, I d expect an array of a single element that is 0.0. This is exactly what you get:
```
"distances": [

    [
        0
    ]
]
```
When you pass two equal points, you ll get:
```
distances": [

    [
        0,
        0
    ]
```

**Comment by boldtrn** [comment]
@oblonski thanks for clearing this up.

> When you pass one point, I d expect an array of a single element that is 0 since the distance from point A to point A is always 0.

That makes sense, yes.

> When you pass two equal points, you ll get ... - This makes sense. Doesnt it?

Yes, if they are equal, that makes sense. To be honest, I haven't thought about the meaning of the request. I think the reason why I expected an error is this statement in the docs:

> Specify at least three points

Maybe we should change the docs in this case?

**Comment by oblonski** [comment]
Yes, you are correct. We should change the docs. I suggest to change the exception when specifying zero points to "Specify at least a single point" or similar.

**Comment by karussell** [comment]
Will do!

**Comment by karussell** [comment]
This should be deployed now. Is this better?

**Comment by oblonski** [comment]
Super. Thanks.
