### ISSUE TITLE
Geocoding external providers

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api#57]
When playing around with the different providers for Geocoding it happened to me that I misswrote one provider. I was suprised to see that I received the geocoding results of the default geocoder. 

Should we throw an exception instead?

**Comment by karussell** [comment]
Yes at the moment but "no" because we could fallback (silently) to the default provider if we e.g. do not support a specific provider

**Comment by boldtrn** [comment]
Ok, I understand. Thanks for clearing this up.
