### ISSUE TITLE
Strange detour

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#59]
[Here](https://graphhopper.com/maps/?point=49.391843%2C11.176862&point=49.390481%2C11.161551) we use a strange detour over the motorway link. The maxspeed for the `motorway` is higher than our default speed for `motorway_link` and so it shouldn't take the detour.

**Comment by boldtrn** [comment]
Yes very weird, I had a brief look at the OSM data, that looks good as well. Distance is almost identical (according to GH), but time seems to be faster via the detour (which shouldn't be true).

**Comment by karussell** [comment]
This was a problem with our improve ETAs that made a wrong decision regarding motorway_link without maxspeed

**Comment by oblonski** [comment]
👍
