### ISSUE TITLE
Progress of beta release for Route Optimization / Tour Optimization API

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#6]
Since End of April our Tour Optimization API is available for selected developers. Since Mid-May it is available for all developers. Keep in mind that it is not yet suitable for production usage. If you intend to use it [please contact us](https://graphhopper.com/#contact) before.

Refer to the following information

 * A work in progress [documentation](https://github.com/graphhopper/directions-api/blob/master/README.md#tour-optimization-api)
 * [Live examples](https://graphhopper.com/api/1/examples/#optimization)

**Comment by karussell** [comment]
This API is now available for all users with the free package (max. 1 vehicle for now). You can always request a free standard package for 6 weeks of course to try everything out. Also we welcome feedback regarding our pricing!

**Comment by karussell** [comment]
Breaking change: using seconds instead milliseconds for time costs

**Comment by karussell** [comment]
The vehicle_type parameters time_dependent_costs and distance_dependent_costs will be removed

**Comment by karussell** [comment]
The solution parameter is now just optional and does not contain 'pending', please use the [status instead](https://github.com/graphhopper/directions-api-js-client/blob/master/js/GraphHopperOptimization.js#L109)

**Comment by oblonski** [comment]
LargeResponse in swagger spec and java client was renamed to Response

**Comment by oblonski** [comment]
time/distance_dependent_costs parameter were removed from swagger spec and java client, thus they are accessible anymore

**Comment by karussell** [comment]
A new speed_factor was introduced for vehicle_types but this is not a breaking change. As well as the [new route editor](https://karussell.wordpress.com/2015/07/21/graphhoppers-new-route-optimization-editor/)

![Route Editor](https://karussell.files.wordpress.com/2015/07/route-editor-overview.png)

**Comment by Geo-Trackers** [comment]
I cloned the direction-api-vrp-javaclient.But i am still confused on how to use it.I am new to Android Programming.Could anyone please explain me in detail on how to use the cloned API on Android Studio.
Thanks in advance.

**Comment by karussell** [comment]
Please see #12 and avoid commenting in unrelated issues.

**Comment by oblonski** [comment]
The API now allows to set an arbitrary number of additional relations between services and shipments (with a simple two-liner in json). It is documented [here](https://github.com/graphhopper/directions-api/blob/master/docs-route-optimization.md#relations).

**Comment by oblonski** [comment]
On 20.09.2015 we are going to activate our new json validator that checks whether the properties of the request json are valid. If not, it immediately gives you feedback on this like this:

```json
{
  "message" : "unable to process json input. check whether your input is valid",
  "hints" : [ {
    "message" : "unsupported json property [driver_name]. allowed properties: [vehicle_id, type_id, start_address, end_address, return_to_depot, earliest_start, latest_end, skills]",
    "details" : "class java.lang.IllegalStateException"
}
```

For the time being, please align your json request according to our specification (see [documentation](https://github.com/graphhopper/directions-api/blob/master/docs-route-optimization.md)), otherwise it will break your code.

**Comment by karussell** [comment]
This is now live and you don't have to expect breaking changes in our Route Optimization API anymore. We are closing here and officially announce the public beta in the next weeks on our blog.

**Comment by git2dinu** [comment]
Please give the web url to show the routing optimization api map instead of editor show.

**Comment by oblonski** [comment]
I did not entirely understand your comment. What do you mean with editor show? If you register to GraphHopper then you have access to the editor via Dashboard - Editor automatically.

**Comment by git2dinu** [comment]
I have route output json. Instead of use editor via Dashboard, is any http url there to see the route map. Such that we can see the route map in anywhere by using web browser.

**Comment by oblonski** [comment]
Ahh ok. Good point. No this is not yet possible. You can just paste your problem.json, optimize and then you can see your output.

**Comment by karussell** [comment]
There is also the open source examples which you can adapt to your needs:
https://github.com/graphhopper/directions-api/blob/master/README.md#api-clients-and-examples

**Comment by git2dinu** [comment]
By using that open source example, still not able to see the map output in routing optimization api (got output as json). And also only can able to see the map output through http url in routing api.

**Comment by karussell** [comment]
Please use our forum if you have [more or detailed questions](https://discuss.graphhopper.com/c/directions-api) and the examples will give you an overview of the result. See them in action [here](https://graphhopper.com/api/1/examples/#optimization).

**Comment by git2dinu** [comment]
Thanks for clarifications

**Comment by git2dinu** [comment]
Hi,

Need one clarifications in Jsprit. By using Jsprit, I have found the list of routes from starting point.
But here my question is , I have one lat lon that lat long is coming as in mid of the list of routes from Jsprit. If I want to go first as that particular lat long from my start location means how to prioritize that lat long? Please suggest me

**Comment by karussell** [comment]
Please use the jsprit mailing list for questions regarding jsprit.

**Comment by oblonski** [comment]
jsprit mailing list: https://groups.google.com/forum/#!forum/jsprit-mailing-list

**Comment by karussell** [comment]
See the [blog post](https://graphhopper.com/blog/2015/11/02/graphhopper-route-optimization-api-goes-beta/) for going beta.
