### ISSUE TITLE
detour for residential

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#60]
One more strange [detour example](https://graphhopper.com/maps/?point=48.70519%2C9.886875&point=48.704585%2C9.888344). The main street is 30, the other streets are residential as well. Somehow, we take the detour through residential, even though it is 17m longer and speed there should be 30 as well.

**Comment by boldtrn** [comment]
Maybe we should debug that sometime. It is a bit odd.

**Comment by karussell** [comment]
We found the reason in our ETA improvement code and will roll out an update soon.

**Comment by karussell** [comment]
A bit late but this is fixed now.
