### ISSUE TITLE
Remove 'in progress'

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api#78]
What is the purpose of 'in progress' here:

https://graphhopper.com/api/1/docs/route-optimization/#vehicle-routing-problem

**Comment by oblonski** [comment]
I should indicate that the json examples for the vehicle routing problems are work in progress. I see that this can be misleading and deleted it. I might delete all examples in the doc ... hmm.

**Comment by oblonski** [comment]
done 
https://graphhopper.com/api/1/docs/route-optimization/#vehicle-routing-problem

**Comment by oblonski** [comment]
> How can an example be "in progress"?
If the documentation - and here specific examples to model a vehicle routing problem - is incomplete, needs to be extended and revised, it is work in progress. Isn't it?

**Comment by karussell** [comment]
Complete in the sense of uses all features? For me an example is about a specific use case and is automatically complete if one reduces the use case requirements :)

**Comment by oblonski** [comment]
Hm ... if you look at the examples for the traveling salesman problem, there is a real story telling how to model tsps with different requirements. I wanted to do the same for vehicle routing problems, but I just had no time or just did not like to do it at that time, therefore, I added this placeholder "in progress" indicating that some day there will be a similar story for modelling vrps.

**Comment by karussell** [comment]
Thanks, clear now :) !
