### ISSUE TITLE
RailWay Routing instead of Car

### ISSUE THREAD

**Issue by sadaqatbukhari** [graphhopper/directions-api#9]
I need to route on railways line using graphhopper instead of car. Could you please guide me how to do that using api?  I need to provide following options http://wiki.openstreetmap.org/wiki/Key:railway.

**Comment by jansoe** [comment]
Public Transport is currently not supported.

**Comment by karussell** [comment]
Public transport is not only a different beast algorithm wise it is also a data coverage problem and therefor we won't support this in the near future. For graphhopper itself and just routing on the railway network without the time information @jansoe already replied here on how to do that: https://github.com/graphhopper/graphhopper/issues/443
